version: '2.1'
services:

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry
    ports:
      - 9999:9999
    depends_on:
      config:
        condition: service_healthy

  book-service:
    build: book-service
    ports:
      - 5000:5000
    depends_on:
      config:
        condition: service_healthy
